# backend/image_gen.py

import os
import requests
from typing import List

DEEPAI_IMAGE_URL = "https://api.deepai.org/api/text2img"


def _get_headers() -> dict:
    """
    Prepare DeepAI authentication headers.
    """
    api_key = os.getenv("DEEPAI_API_KEY")
    if not api_key:
        raise RuntimeError("DEEPAI_API_KEY not set")
    return {
        "api-key": api_key
    }


def generate_images(prompt: str, tags: List[str], count: int = 3) -> List[str]:
    """
    Generate images using DeepAI text-to-image API.

    Args:
        prompt: Original user prompt
        tags: Visual tags generated by logic layer
        count: Number of images to generate (1–6)

    Returns:
        List of image URLs
    """

    # Enrich prompt slightly for better image results
    enriched_prompt = prompt
    if tags:
        enriched_prompt += ". Visual style: " + ", ".join(tags)

    images: List[str] = []

    for _ in range(count):
        response = requests.post(
            DEEPAI_IMAGE_URL,
            headers=_get_headers(),
            data={
                "text": enriched_prompt
            },
            timeout=30
        )

        response.raise_for_status()

        data = response.json()

        # DeepAI returns image URL under "output_url"
        image_url = data.get("output_url")
        if image_url:
            images.append(image_url)

    return images
